const salary = {
  low: "\u00a323,000\u2013\u00a327,000",
  entry: "\u00a324,000\u2013\u00a328,000",
  standard: "\u00a325,000\u2013\u00a330,000",
  strong: "\u00a328,000\u2013\u00a335,000",
  high: "\u00a330,000\u2013\u00a338,000",
  competitive: "Competitive / dependent on experience"
};

const baseJob = {
  status: "active",
  sourceLabel: "Local demo seed",
  applyLink: "#",
  seniorityScore: 1,
  remoteCompatible: false,
  earlyCareerFriendly: true,
  trainingProvided: true,
  requiresSecurityClearance: false,
  requiresDriving: false,
  requiresPhD: false,
  requiresPriorForensicExperience: false,
  requiresGCP: false,
  requiresSQL: false,
  requiresPython: false,
  requiresLabExperience: false,
  requiresTravel: false,
  minimumDegreeGrade: "",
  locationFlexibility: "Regional",
  sector: "Healthcare and STEM"
};

function job(data) {
  return {
    ...baseJob,
    ...data,
    style: data.workStyle,
    score: data.score || 74,
    tags: data.tags || [],
    requiredSkills: data.requiredSkills || [],
    preferredSkills: data.preferredSkills || [],
    requirements: data.requirements || [],
    description: data.description || data.summary,
    note: data.note || "Check the exact requirements, location rules, and training support before applying."
  };
}

const seededJobs = [
  job({
    id: "forensic-lab-assistant-bham",
    title: "Forensic Laboratory Assistant",
    company: "Midlands Forensic Services",
    category: "Forensic science / toxicology / evidence",
    location: "Birmingham",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Supports sample receipt, laboratory preparation, documentation, and quality checks in a forensic testing environment.",
    description: "A structured entry route into forensic laboratory support with chain-of-custody awareness, sample handling, and clear SOPs.",
    requiredSkills: ["sample handling", "documentation", "attention to detail", "laboratory safety"],
    preferredSkills: ["biomedical science", "microscopy", "chain of custody", "quality control"],
    requirements: ["science degree or equivalent lab experience", "accurate records", "on-site attendance"],
    experienceRequired: "Entry-level laboratory experience desirable",
    educationLevel: "BSc or equivalent science background",
    tags: ["forensic", "lab", "evidence", "entry-level", "Birmingham"],
    requiresLabExperience: true,
    requiresPriorForensicExperience: false,
    locationFlexibility: "Birmingham on-site",
    sector: "Forensic science"
  }),
  job({
    id: "toxicology-lab-support-manchester",
    title: "Toxicology Laboratory Support Assistant",
    company: "Northern Analytical Toxicology",
    category: "Forensic science / toxicology / evidence",
    location: "Manchester",
    workStyle: "On-site",
    level: "Entry-level",
    salary: salary.entry,
    summary: "Prepares toxicology samples, logs results, and supports analysts with evidence handling and lab housekeeping.",
    description: "A practical lab support role for candidates interested in analytical toxicology and regulated evidence workflows.",
    requiredSkills: ["lab safety", "sample preparation", "data recording", "attention to detail"],
    preferredSkills: ["analytical chemistry", "toxicology", "Excel", "quality systems"],
    requirements: ["science qualification", "on-site work", "right to work checks"],
    experienceRequired: "0-1 years",
    educationLevel: "Science A-levels or degree preferred",
    tags: ["toxicology", "forensic", "lab support", "entry-level"],
    requiresLabExperience: true,
    locationFlexibility: "Manchester on-site",
    sector: "Forensic toxicology"
  }),
  job({
    id: "evidence-documentation-assistant-london",
    title: "Evidence Documentation Assistant",
    company: "CaseTrace UK",
    category: "Forensic science / toxicology / evidence",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Maintains evidence records, prepares case bundles, and checks documentation quality for forensic casework teams.",
    description: "A documentation-heavy role suited to strong writers with scientific awareness and careful record keeping.",
    requiredSkills: ["documentation", "Excel", "quality checks", "communication"],
    preferredSkills: ["chain of custody", "scientific writing", "casework administration"],
    requirements: ["accurate record keeping", "hybrid London availability"],
    experienceRequired: "Administrative or lab documentation experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["evidence", "documentation", "forensic", "hybrid", "London"],
    remoteCompatible: true,
    locationFlexibility: "Hybrid London",
    sector: "Forensic operations"
  }),
  job({
    id: "forensic-casework-support-officer-leeds",
    title: "Forensic Casework Support Officer",
    company: "West Yorkshire Scientific Support",
    category: "Forensic science / toxicology / evidence",
    location: "Leeds",
    workStyle: "On-site",
    level: "Early professional",
    salary: salary.strong,
    summary: "Coordinates case materials, communicates with scientists, and supports timely forensic case progression.",
    description: "Bridges scientific teams and case administration, with exposure to regulated forensic workflows.",
    requiredSkills: ["case administration", "communication", "data entry", "attention to detail"],
    preferredSkills: ["forensic casework", "quality assurance", "evidence handling"],
    requirements: ["security eligibility checks", "on-site casework support"],
    experienceRequired: "1-2 years in scientific admin or case support",
    educationLevel: "Degree preferred",
    tags: ["forensic", "casework", "evidence", "Leeds"],
    requiresSecurityClearance: true,
    locationFlexibility: "Leeds on-site",
    sector: "Forensic casework"
  }),
  job({
    id: "dna-lab-support-technician-cambridge",
    title: "DNA Laboratory Support Technician",
    company: "Helix Evidence Labs",
    category: "Forensic science / toxicology / evidence",
    location: "Cambridge",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports DNA sample processing, reagent preparation, contamination control, and laboratory documentation.",
    description: "A science-led entry role for candidates with molecular biology awareness and strong lab discipline.",
    requiredSkills: ["molecular biology", "lab safety", "documentation", "quality control"],
    preferredSkills: ["DNA", "PCR", "biomedical science", "contamination control"],
    requirements: ["science degree", "on-site laboratory work"],
    experienceRequired: "Placement or university lab experience",
    educationLevel: "BSc Biomedical Science or related subject",
    tags: ["DNA", "forensic", "molecular biology", "lab", "Cambridge"],
    requiresLabExperience: true,
    locationFlexibility: "Cambridge on-site",
    sector: "Forensic biology"
  }),
  job({
    id: "analytical-chemistry-assistant-oxford",
    title: "Analytical Chemistry Assistant",
    company: "Oxbridge Analytical",
    category: "Forensic science / toxicology / evidence",
    location: "Oxford",
    workStyle: "On-site",
    level: "Entry-level",
    salary: salary.standard,
    summary: "Supports sample preparation, instrument logs, chromatography runs, and chemical analysis documentation.",
    description: "A hands-on analytical support role with transferable relevance to toxicology and forensic chemistry.",
    requiredSkills: ["chemistry", "sample preparation", "Excel", "lab records"],
    preferredSkills: ["HPLC", "GC-MS", "toxicology", "quality systems"],
    requirements: ["chemistry or bioscience background", "on-site lab availability"],
    experienceRequired: "University lab experience accepted",
    educationLevel: "BSc or equivalent science background",
    tags: ["analytical chemistry", "toxicology", "lab", "Oxford"],
    requiresLabExperience: true,
    locationFlexibility: "Oxford on-site",
    sector: "Analytical science"
  }),
  job({
    id: "crime-lab-support-assistant-london",
    title: "Crime Laboratory Support Assistant",
    company: "Metropolitan Science Unit",
    category: "Forensic science / toxicology / evidence",
    location: "London",
    workStyle: "On-site",
    level: "Entry-level",
    salary: salary.standard,
    summary: "Receives exhibits, supports laboratory preparation, and maintains controlled documentation for crime laboratory teams.",
    description: "A regulated lab support role with strong emphasis on accuracy, evidence processes, and teamwork.",
    requiredSkills: ["evidence logging", "lab safety", "teamwork", "accurate records"],
    preferredSkills: ["chain of custody", "forensic science", "biomedical science"],
    requirements: ["security checks", "on-site shift pattern"],
    experienceRequired: "Entry-level with science background",
    educationLevel: "Science degree preferred",
    tags: ["crime lab", "forensic", "evidence", "London"],
    requiresSecurityClearance: true,
    requiresLabExperience: true,
    locationFlexibility: "London on-site",
    sector: "Crime laboratory"
  }),
  job({
    id: "forensic-quality-admin-hybrid-uk",
    title: "Forensic Quality Administration Assistant",
    company: "ForenQual Partners",
    category: "Forensic science / toxicology / evidence",
    location: "Hybrid UK",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.entry,
    summary: "Supports audit trails, SOP updates, training logs, and controlled document reviews for forensic quality teams.",
    description: "A quality documentation role for candidates who enjoy structured evidence, scientific writing, and process detail.",
    requiredSkills: ["documentation", "quality assurance", "Excel", "organisation"],
    preferredSkills: ["SOPs", "scientific writing", "regulated environments"],
    requirements: ["hybrid meetings", "careful document control"],
    experienceRequired: "Administrative or scientific writing experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["forensic quality", "documentation", "hybrid", "quality assurance"],
    remoteCompatible: true,
    locationFlexibility: "Hybrid UK",
    sector: "Forensic quality"
  }),

  job({
    id: "research-assistant-neuro-bham",
    title: "Research Assistant, Neuroscience Lab",
    company: "Birmingham NeuroDiscovery",
    category: "Biomedical research / lab support",
    location: "Birmingham",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Assists with microscopy, cell staining, experimental records, literature review, and research data handling.",
    description: "A biomedical research support role aligned with microscopy, scientific writing, and dissertation experience.",
    requiredSkills: ["microscopy", "literature review", "data recording", "lab safety"],
    preferredSkills: ["immunohistochemistry", "confocal microscopy", "ImageJ", "GraphPad Prism"],
    requirements: ["bioscience degree", "on-site lab work"],
    experienceRequired: "University research project or placement",
    educationLevel: "BSc Biomedical Science or related",
    tags: ["biomedical research", "neuroscience", "microscopy", "Birmingham"],
    requiresLabExperience: true,
    sector: "Biomedical research"
  }),
  job({
    id: "biomedical-lab-technician-london",
    title: "Biomedical Laboratory Technician",
    company: "Thames Translational Medicine",
    category: "Biomedical research / lab support",
    location: "London",
    workStyle: "On-site",
    level: "Early professional",
    salary: salary.high,
    summary: "Maintains laboratory workflows, prepares samples, supports assays, and records research outputs for translational studies.",
    description: "A practical lab role with good fit for biomedical science graduates with strong record keeping.",
    requiredSkills: ["sample preparation", "lab records", "assay support", "teamwork"],
    preferredSkills: ["cell culture", "ELISA", "biomedical science"],
    requirements: ["lab experience", "London on-site"],
    experienceRequired: "6-18 months lab experience desirable",
    educationLevel: "BSc Biomedical Science or related",
    tags: ["biomedical", "lab technician", "translational medicine"],
    requiresLabExperience: true,
    seniorityScore: 2,
    sector: "Translational research"
  }),
  job({
    id: "graduate-lab-assistant-cambridge",
    title: "Graduate Laboratory Assistant",
    company: "Cambridge Cell Systems",
    category: "Biomedical research / lab support",
    location: "Cambridge",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Supports cell biology experiments, reagent tracking, microscopy scheduling, and lab inventory.",
    description: "A graduate-friendly lab assistant role with structured training and transferable cell biology exposure.",
    requiredSkills: ["lab safety", "cell biology", "organisation", "data recording"],
    preferredSkills: ["cell culture", "microscopy", "Excel"],
    requirements: ["science degree", "on-site attendance"],
    experienceRequired: "University laboratory experience",
    educationLevel: "BSc life sciences",
    tags: ["graduate", "lab assistant", "cell biology", "Cambridge"],
    requiresLabExperience: true,
    sector: "Cell biology"
  }),
  job({
    id: "cell-culture-technician-oxford",
    title: "Cell Culture Technician",
    company: "Oxford BioModels",
    category: "Biomedical research / lab support",
    location: "Oxford",
    workStyle: "On-site",
    level: "Early professional",
    salary: salary.high,
    summary: "Maintains cell lines, records experiments, supports assay setup, and follows contamination-control procedures.",
    description: "A more specialised lab role that may suit candidates with placement or dissertation cell culture experience.",
    requiredSkills: ["cell culture", "aseptic technique", "lab records", "quality control"],
    preferredSkills: ["microscopy", "GraphPad Prism", "experimental design"],
    requirements: ["hands-on cell culture experience"],
    experienceRequired: "1+ year or strong placement experience",
    educationLevel: "BSc or MSc life sciences",
    tags: ["cell culture", "biomedical", "Oxford", "lab"],
    requiresLabExperience: true,
    seniorityScore: 2,
    sector: "Biomedical research"
  }),
  job({
    id: "microscopy-research-assistant-leeds",
    title: "Microscopy Research Assistant",
    company: "Leeds Imaging Hub",
    category: "Biomedical research / lab support",
    location: "Leeds",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Prepares imaging sessions, assists with image analysis, and supports researchers with microscopy documentation.",
    description: "A strong fit for candidates with ImageJ, microscopy, and scientific reporting exposure.",
    requiredSkills: ["microscopy", "image analysis", "documentation", "Excel"],
    preferredSkills: ["FIJI", "ImageJ", "confocal microscopy", "scientific writing"],
    requirements: ["bioscience degree", "on-site imaging support"],
    experienceRequired: "University project experience accepted",
    educationLevel: "BSc science background",
    tags: ["microscopy", "ImageJ", "research assistant", "Leeds"],
    requiresLabExperience: true,
    sector: "Research imaging"
  }),
  job({
    id: "translational-research-assistant-manchester",
    title: "Translational Research Assistant",
    company: "Manchester Precision Health",
    category: "Biomedical research / lab support",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports translational studies through literature review, sample tracking, data entry, and research documentation.",
    description: "A hybrid biomedical research support role balancing lab coordination and scientific documentation.",
    requiredSkills: ["literature review", "data entry", "sample tracking", "scientific writing"],
    preferredSkills: ["biomedical science", "clinical research", "Excel"],
    requirements: ["science degree", "hybrid Manchester availability"],
    experienceRequired: "Entry-level with research project evidence",
    educationLevel: "BSc biomedical or related subject",
    tags: ["translational medicine", "research", "hybrid", "Manchester"],
    remoteCompatible: true,
    locationFlexibility: "Hybrid Manchester",
    sector: "Translational medicine"
  }),
  job({
    id: "junior-research-ops-associate-remote",
    title: "Junior Research Operations Associate",
    company: "Luma Labs",
    category: "Biomedical research / lab support",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Supports study logistics, research notes, participant scheduling, and structured insight documentation.",
    description: "A remote-friendly research operations role where writing, organisation, and stakeholder communication matter.",
    requiredSkills: ["research operations", "writing", "organisation", "stakeholder communication"],
    preferredSkills: ["health research", "Excel", "data analysis"],
    requirements: ["remote collaboration", "clear written communication"],
    experienceRequired: "Research or coordination experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["research operations", "remote", "writing", "coordination"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Research operations"
  }),
  job({
    id: "cancer-research-admin-assistant-bham",
    title: "Cancer Research Administration Assistant",
    company: "West Midlands Oncology Research",
    category: "Biomedical research / lab support",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.entry,
    summary: "Coordinates research documentation, meeting notes, sample logs, and literature searches for oncology studies.",
    description: "A graduate-friendly role connecting biomedical knowledge, cancer research interest, and documentation strengths.",
    requiredSkills: ["scientific writing", "organisation", "Excel", "literature search"],
    preferredSkills: ["cancer research", "biomedical science", "stakeholder communication"],
    requirements: ["hybrid Birmingham availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Science degree preferred",
    tags: ["cancer research", "documentation", "hybrid", "Birmingham"],
    remoteCompatible: true,
    sector: "Cancer research"
  }),

  job({
    id: "clinical-trials-assistant-london",
    title: "Clinical Trials Assistant",
    company: "St Clements Clinical Research",
    category: "Clinical research / trials",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports trial documentation, site files, participant tracking, and research team coordination.",
    description: "A structured entry route into clinical research with document control and patient-data awareness.",
    requiredSkills: ["documentation", "organisation", "Excel", "communication"],
    preferredSkills: ["GCP awareness", "clinical research", "patient data"],
    requirements: ["accurate records", "hybrid London availability"],
    experienceRequired: "Entry-level, healthcare or research exposure helpful",
    educationLevel: "Life science degree preferred",
    tags: ["clinical trials", "GCP", "documentation", "London"],
    requiresGCP: false,
    remoteCompatible: true,
    sector: "Clinical research"
  }),
  job({
    id: "clinical-research-support-coordinator-bham",
    title: "Clinical Research Support Coordinator",
    company: "Birmingham Health Studies Unit",
    category: "Clinical research / trials",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.standard,
    summary: "Coordinates study documents, participant communications, data checks, and research team calendars.",
    description: "A supportive clinical research role for candidates with organisation, writing, and healthcare-facing experience.",
    requiredSkills: ["coordination", "communication", "data checks", "documentation"],
    preferredSkills: ["healthcare volunteering", "clinical research", "Excel"],
    requirements: ["hybrid Birmingham work", "confidential data handling"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["clinical research", "Birmingham", "hybrid", "coordination"],
    remoteCompatible: true,
    sector: "Clinical research"
  }),
  job({
    id: "research-study-assistant-leeds",
    title: "Research Study Assistant",
    company: "Leeds Teaching Hospitals Research",
    category: "Clinical research / trials",
    location: "Leeds",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.entry,
    summary: "Helps prepare study packs, records participant updates, and supports research nurses with study administration.",
    description: "A patient-adjacent research support role with training in research documentation and study workflows.",
    requiredSkills: ["attention to detail", "communication", "documentation", "teamwork"],
    preferredSkills: ["NHS exposure", "patient-facing experience", "Excel"],
    requirements: ["on-site hospital work", "confidentiality"],
    experienceRequired: "Entry-level",
    educationLevel: "Life science or healthcare background helpful",
    tags: ["clinical study", "NHS", "patient data", "Leeds"],
    sector: "NHS research"
  }),
  job({
    id: "trial-documentation-assistant-remote",
    title: "Trial Documentation Assistant",
    company: "ClearPath Trials",
    category: "Clinical research / trials",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Checks trial documents, maintains file trackers, and supports remote clinical operations teams.",
    description: "A remote-first role for candidates with strong documentation and regulated-process strengths.",
    requiredSkills: ["document control", "Excel", "quality checks", "written communication"],
    preferredSkills: ["GCP awareness", "clinical trials", "regulated documentation"],
    requirements: ["remote working discipline", "UK working hours"],
    experienceRequired: "Documentation experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["clinical trials", "documentation", "remote", "GCP"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Clinical operations"
  }),
  job({
    id: "patient-data-coordinator-manchester",
    title: "Patient Data Coordinator",
    company: "NorthCare Research Network",
    category: "Clinical research / trials",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.standard,
    summary: "Maintains patient study trackers, resolves data queries, and prepares simple reporting for research teams.",
    description: "A data coordination role balancing healthcare sensitivity, Excel, and careful documentation.",
    requiredSkills: ["Excel", "data entry", "confidentiality", "communication"],
    preferredSkills: ["clinical research", "NHS data", "service improvement"],
    requirements: ["hybrid Manchester availability", "data accuracy"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["patient data", "clinical research", "Excel", "Manchester"],
    remoteCompatible: true,
    sector: "Clinical data"
  }),
  job({
    id: "clinical-research-admin-cambridge",
    title: "Clinical Research Administrator",
    company: "Cambridge Rare Disease Studies",
    category: "Clinical research / trials",
    location: "Cambridge",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports ethics files, study setup, site correspondence, and participant documentation.",
    description: "A life-science graduate route into clinical research administration with structured mentoring.",
    requiredSkills: ["ethics documentation", "organisation", "writing", "Excel"],
    preferredSkills: ["biomedical science", "GCP awareness", "rare disease research"],
    requirements: ["hybrid Cambridge availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Life science degree preferred",
    tags: ["clinical research", "administrator", "Cambridge", "ethics"],
    remoteCompatible: true,
    sector: "Clinical research"
  }),
  job({
    id: "clinical-trial-data-assistant-oxford",
    title: "Clinical Trial Data Assistant",
    company: "Oxford Trials Collective",
    category: "Clinical research / trials",
    location: "Oxford, hybrid",
    workStyle: "Hybrid",
    level: "Early professional",
    salary: salary.strong,
    summary: "Supports data query resolution, trial database checks, and research documentation for multi-site studies.",
    description: "A stronger data-focused clinical trial role requiring accuracy and some database confidence.",
    requiredSkills: ["data quality", "Excel", "database checks", "documentation"],
    preferredSkills: ["SQL", "clinical trials", "GCP"],
    requirements: ["trial data experience desirable"],
    experienceRequired: "6-18 months data or trial admin experience",
    educationLevel: "Degree preferred",
    tags: ["clinical data", "trial database", "Oxford", "hybrid"],
    requiresSQL: true,
    remoteCompatible: true,
    seniorityScore: 2,
    sector: "Clinical data"
  }),
  job({
    id: "research-governance-assistant-london",
    title: "Research Governance Assistant",
    company: "London Health Research Office",
    category: "Clinical research / trials",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.entry,
    summary: "Assists with governance submissions, study approvals, document tracking, and research compliance records.",
    description: "A process-led research support role for candidates with careful documentation and healthcare interest.",
    requiredSkills: ["document tracking", "organisation", "communication", "attention to detail"],
    preferredSkills: ["NHS", "research governance", "ethics"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Administrative experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["research governance", "ethics", "documentation", "London"],
    remoteCompatible: true,
    sector: "Research governance"
  }),

  job({
    id: "graduate-insight-analyst-bham",
    title: "Graduate Insight Analyst",
    company: "Northstar Health",
    category: "Healthcare data / insight / analyst",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports research projects, reports, dashboards, and service-improvement insight for healthcare teams.",
    description: "A strong graduate analyst role for Excel, research methods, scientific writing, and stakeholder communication.",
    requiredSkills: ["Excel", "data analysis", "research methods", "report writing"],
    preferredSkills: ["SQL", "healthcare data", "Power BI", "stakeholder communication"],
    requirements: ["hybrid Birmingham availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["insight analyst", "healthcare", "Excel", "Birmingham"],
    requiresSQL: false,
    remoteCompatible: true,
    sector: "Healthcare insight"
  }),
  job({
    id: "health-data-assistant-remote",
    title: "Health Data Assistant",
    company: "CareMetrics UK",
    category: "Healthcare data / insight / analyst",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Entry-level",
    salary: salary.standard,
    summary: "Cleans healthcare datasets, updates trackers, and prepares simple insight summaries for service teams.",
    description: "A remote-friendly data assistant role where Excel, accuracy, and healthcare interest matter more than advanced coding.",
    requiredSkills: ["Excel", "data cleaning", "attention to detail", "reporting"],
    preferredSkills: ["health data", "Power BI", "SQL"],
    requirements: ["UK working hours", "remote collaboration"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["health data", "remote", "Excel", "entry-level"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Healthcare data"
  }),
  job({
    id: "service-improvement-analyst-leeds",
    title: "Service Improvement Analyst",
    company: "Leeds Care Improvement",
    category: "Healthcare data / insight / analyst",
    location: "Leeds, hybrid",
    workStyle: "Hybrid",
    level: "Early professional",
    salary: salary.high,
    summary: "Analyses service data, maps processes, and prepares recommendations for healthcare improvement projects.",
    description: "A practical improvement analyst role for candidates with analysis, communication, and healthcare-facing experience.",
    requiredSkills: ["Excel", "process mapping", "data analysis", "communication"],
    preferredSkills: ["NHS", "service improvement", "Power BI"],
    requirements: ["hybrid Leeds availability"],
    experienceRequired: "1+ year analyst or project support experience desirable",
    educationLevel: "Degree or equivalent experience",
    tags: ["service improvement", "healthcare", "analysis", "Leeds"],
    remoteCompatible: true,
    seniorityScore: 2,
    sector: "Service improvement"
  }),
  job({
    id: "nhs-data-coordinator-london",
    title: "NHS Data Coordinator",
    company: "London Integrated Care Analytics",
    category: "Healthcare data / insight / analyst",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Coordinates NHS data returns, validates spreadsheets, and supports programme reporting.",
    description: "An early-career data coordination role with clear requirements and structured NHS reporting processes.",
    requiredSkills: ["Excel", "data validation", "organisation", "reporting"],
    preferredSkills: ["NHS data", "SQL", "stakeholder communication"],
    requirements: ["hybrid London availability", "data confidentiality"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["NHS", "data coordinator", "Excel", "London"],
    remoteCompatible: true,
    sector: "NHS analytics"
  }),
  job({
    id: "research-data-analyst-cambridge",
    title: "Research Data Analyst",
    company: "Cambridge Translational Data",
    category: "Healthcare data / insight / analyst",
    location: "Cambridge, hybrid",
    workStyle: "Hybrid",
    level: "Early professional",
    salary: salary.high,
    summary: "Analyses research datasets, prepares figures, and supports scientific teams with data interpretation.",
    description: "A data-heavy research role aligned with GraphPad, R basics, Excel, and scientific reporting.",
    requiredSkills: ["data analysis", "Excel", "scientific reporting", "research methods"],
    preferredSkills: ["R", "GraphPad Prism", "bioinformatics", "statistics"],
    requirements: ["research data experience"],
    experienceRequired: "Research project or 1+ year data experience",
    educationLevel: "Science degree preferred",
    tags: ["research data", "GraphPad", "R", "Cambridge"],
    requiresLabExperience: false,
    remoteCompatible: true,
    seniorityScore: 2,
    sector: "Research analytics"
  }),
  job({
    id: "early-careers-data-coordinator-london",
    title: "Early Careers Data Coordinator",
    company: "Civic Futures",
    category: "Healthcare data / insight / analyst",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.high,
    summary: "Maintains programme data, prepares reports, and tracks early-career participant outcomes.",
    description: "Blends people-focused work with data organisation, reporting, and a supportive training environment.",
    requiredSkills: ["Excel", "data organisation", "report writing", "stakeholder communication"],
    preferredSkills: ["dashboard tools", "public sector", "service evaluation"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["early careers", "data coordinator", "London", "hybrid"],
    remoteCompatible: true,
    sector: "Programme data"
  }),
  job({
    id: "population-health-analyst-assistant-manchester",
    title: "Population Health Analyst Assistant",
    company: "Greater Manchester Health Insights",
    category: "Healthcare data / insight / analyst",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Supports population health analysis, spreadsheet checks, and evidence summaries for local health projects.",
    description: "A graduate-friendly health analytics role with structured support and public-health relevance.",
    requiredSkills: ["Excel", "data analysis", "literature review", "communication"],
    preferredSkills: ["public health", "Power BI", "NHS"],
    requirements: ["hybrid Manchester availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["population health", "data", "public health", "Manchester"],
    remoteCompatible: true,
    sector: "Population health"
  }),
  job({
    id: "junior-biomedical-data-assistant-oxford",
    title: "Junior Biomedical Data Assistant",
    company: "Oxford BioData Unit",
    category: "Healthcare data / insight / analyst",
    location: "Oxford",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Curates biomedical datasets, checks metadata, and prepares simple summaries for research teams.",
    description: "A bridge role between biomedical science and data analysis for candidates with careful documentation skills.",
    requiredSkills: ["biomedical science", "Excel", "data recording", "attention to detail"],
    preferredSkills: ["R", "bioinformatics", "gene expression analysis"],
    requirements: ["hybrid Oxford availability"],
    experienceRequired: "Entry-level with research project evidence",
    educationLevel: "BSc biomedical or related subject",
    tags: ["biomedical data", "Oxford", "research", "Excel"],
    remoteCompatible: true,
    sector: "Biomedical data"
  }),

  job({
    id: "digital-health-project-assistant-remote",
    title: "Digital Health Project Assistant",
    company: "PulseBridge Digital",
    category: "Digital health / health tech",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Supports digital health project plans, user feedback tracking, documentation, and stakeholder updates.",
    description: "A broad digital health role that rewards organisation, writing, and healthcare interest.",
    requiredSkills: ["project support", "documentation", "stakeholder communication", "organisation"],
    preferredSkills: ["digital health", "user research", "healthcare"],
    requirements: ["remote collaboration", "UK working hours"],
    experienceRequired: "Entry-level project or research support experience",
    educationLevel: "Degree or equivalent experience",
    tags: ["digital health", "remote", "project support", "healthtech"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Digital health"
  }),
  job({
    id: "health-innovation-coordinator-bham",
    title: "Health Innovation Coordinator",
    company: "Birmingham Health Innovation Hub",
    category: "Digital health / health tech",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Coordinates innovation pilots, gathers user feedback, and prepares reports for health technology teams.",
    description: "A hybrid role connecting healthcare, research, stakeholder communication, and emerging products.",
    requiredSkills: ["coordination", "research notes", "communication", "report writing"],
    preferredSkills: ["digital health", "user research", "NHS"],
    requirements: ["hybrid Birmingham availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["health innovation", "Birmingham", "digital health", "hybrid"],
    remoteCompatible: true,
    sector: "Health innovation"
  }),
  job({
    id: "user-research-assistant-digital-health-london",
    title: "User Research Assistant, Digital Health",
    company: "Mindful Metrics",
    category: "Digital health / health tech",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.strong,
    summary: "Helps run user interviews, synthesise notes, and document insights for digital health products.",
    description: "A research-adjacent role where scientific writing, empathy, and structured analysis transfer well.",
    requiredSkills: ["user research", "note synthesis", "writing", "stakeholder communication"],
    preferredSkills: ["health tech", "qualitative research", "clinical context"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Research project or user research exposure helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["user research", "digital health", "London", "insight"],
    remoteCompatible: true,
    sector: "Health technology"
  }),
  job({
    id: "product-research-support-associate-remote",
    title: "Product Research Support Associate",
    company: "CareLoop Labs",
    category: "Digital health / health tech",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Supports product research operations, insight documentation, participant scheduling, and feedback analysis.",
    description: "An adjacent opportunity for candidates with research, writing, and communication strengths.",
    requiredSkills: ["research operations", "documentation", "communication", "organisation"],
    preferredSkills: ["product research", "digital health", "Excel"],
    requirements: ["remote collaboration", "structured documentation"],
    experienceRequired: "Entry-level research support experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["product research", "remote", "healthtech", "research ops"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Health technology"
  }),
  job({
    id: "cognitive-health-app-research-assistant-cambridge",
    title: "Cognitive Health App Research Assistant",
    company: "NeuroSpark Health",
    category: "Digital health / health tech",
    location: "Cambridge, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports research for cognitive screening app features, evidence reviews, and user feedback documentation.",
    description: "A strong fit for candidates with neuroscience interest, digital health projects, and scientific writing.",
    requiredSkills: ["literature review", "research documentation", "user feedback", "scientific writing"],
    preferredSkills: ["cognitive health", "digital health", "neuroscience"],
    requirements: ["hybrid Cambridge availability"],
    experienceRequired: "Entry-level with research project experience",
    educationLevel: "Science or psychology degree preferred",
    tags: ["cognitive health", "digital health", "Cambridge", "research"],
    remoteCompatible: true,
    sector: "Digital health research"
  }),
  job({
    id: "junior-healthtech-analyst-manchester",
    title: "Junior HealthTech Analyst",
    company: "MediNova Analytics",
    category: "Digital health / health tech",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.high,
    summary: "Analyses product usage data, prepares insight summaries, and supports healthtech implementation teams.",
    description: "A data-adjacent healthtech role for candidates with Excel, reporting, and healthcare interest.",
    requiredSkills: ["Excel", "data analysis", "reporting", "stakeholder communication"],
    preferredSkills: ["SQL", "product analytics", "digital health"],
    requirements: ["hybrid Manchester availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["healthtech analyst", "data", "Manchester", "hybrid"],
    requiresSQL: false,
    remoteCompatible: true,
    sector: "Health technology"
  }),
  job({
    id: "health-ai-evaluation-assistant-remote",
    title: "Health AI Evaluation Assistant",
    company: "SafeSignal Health",
    category: "Digital health / health tech",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Entry-level",
    salary: salary.strong,
    summary: "Reviews health AI outputs, logs evaluation notes, and supports evidence summaries for product teams.",
    description: "A local demo role showing how scientific writing and careful evaluation can transfer into health AI.",
    requiredSkills: ["evaluation", "scientific writing", "documentation", "attention to detail"],
    preferredSkills: ["digital health", "evidence review", "data analysis"],
    requirements: ["remote work", "careful judgement"],
    experienceRequired: "Entry-level with research or writing experience",
    educationLevel: "Science or healthcare background helpful",
    tags: ["health AI", "remote", "evaluation", "evidence"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Health AI"
  }),
  job({
    id: "implementation-support-healthtech-leeds",
    title: "HealthTech Implementation Support Assistant",
    company: "Leeds Digital Care",
    category: "Digital health / health tech",
    location: "Leeds, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.entry,
    summary: "Supports healthtech rollouts, training schedules, user feedback logs, and issue documentation.",
    description: "A supportive implementation role with clear requirements and training for early-career candidates.",
    requiredSkills: ["coordination", "communication", "documentation", "problem solving"],
    preferredSkills: ["NHS", "digital health", "training support"],
    requirements: ["hybrid Leeds availability"],
    experienceRequired: "Entry-level coordination experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["implementation", "healthtech", "Leeds", "training"],
    remoteCompatible: true,
    sector: "Digital implementation"
  }),

  job({
    id: "public-health-project-assistant-london",
    title: "Public Health Project Assistant",
    company: "London Prevention Partnership",
    category: "Public health / NHS / service improvement",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Supports public health projects, meeting notes, evidence reviews, and community programme reporting.",
    description: "A graduate-friendly public health route for candidates with research, writing, and communication strengths.",
    requiredSkills: ["project support", "literature review", "report writing", "communication"],
    preferredSkills: ["public health", "community health", "Excel"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["public health", "project assistant", "London", "evidence"],
    remoteCompatible: true,
    sector: "Public health"
  }),
  job({
    id: "population-health-data-assistant-bham",
    title: "Population Health Data Assistant",
    company: "Birmingham Population Health Unit",
    category: "Public health / NHS / service improvement",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.entry,
    summary: "Maintains public health data trackers, supports reporting, and prepares evidence notes for local programmes.",
    description: "A steady entry role combining Excel, public health interest, and structured analytical work.",
    requiredSkills: ["Excel", "data entry", "evidence notes", "organisation"],
    preferredSkills: ["public health", "NHS", "service evaluation"],
    requirements: ["hybrid Birmingham availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["population health", "Birmingham", "data", "public health"],
    remoteCompatible: true,
    sector: "Population health"
  }),
  job({
    id: "nhs-service-improvement-support-officer-manchester",
    title: "NHS Service Improvement Support Officer",
    company: "Manchester Integrated Care",
    category: "Public health / NHS / service improvement",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Supports improvement workshops, action logs, pathway mapping, and simple data summaries.",
    description: "A clear, supported role where communication and structured documentation matter.",
    requiredSkills: ["coordination", "process mapping", "Excel", "communication"],
    preferredSkills: ["NHS", "service improvement", "stakeholder engagement"],
    requirements: ["hybrid Manchester availability"],
    experienceRequired: "Entry-level project support experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["NHS", "service improvement", "Manchester", "support"],
    remoteCompatible: true,
    sector: "NHS improvement"
  }),
  job({
    id: "health-programme-assistant-leeds",
    title: "Health Programme Assistant",
    company: "Leeds Community Health Alliance",
    category: "Public health / NHS / service improvement",
    location: "Leeds, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.low,
    summary: "Supports community health programme delivery, monitoring spreadsheets, and stakeholder communications.",
    description: "A people-focused early-career role with good training and realistic entry requirements.",
    requiredSkills: ["programme support", "communication", "Excel", "organisation"],
    preferredSkills: ["community health", "volunteering", "service evaluation"],
    requirements: ["hybrid Leeds availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["health programme", "community health", "Leeds", "entry-level"],
    remoteCompatible: true,
    sector: "Community health"
  }),
  job({
    id: "community-health-insights-coordinator-remote",
    title: "Community Health Insights Coordinator",
    company: "Neighbourhood Health Lab",
    category: "Public health / NHS / service improvement",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Gathers community feedback, organises insight notes, and prepares summaries for health improvement teams.",
    description: "A remote-friendly insight role for candidates with writing, communication, and healthcare-facing experience.",
    requiredSkills: ["insight synthesis", "communication", "writing", "organisation"],
    preferredSkills: ["public health", "qualitative research", "community engagement"],
    requirements: ["remote working", "structured note-taking"],
    experienceRequired: "Entry-level with volunteering or research experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["community health", "insight", "remote", "public health"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Community insights"
  }),
  job({
    id: "health-equity-research-assistant-london",
    title: "Health Equity Research Assistant",
    company: "Equity Evidence Collective",
    category: "Public health / NHS / service improvement",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Supports literature reviews, qualitative coding, evidence summaries, and programme evaluation for health equity projects.",
    description: "A research-led public health role for candidates with literature review and scientific writing strengths.",
    requiredSkills: ["literature review", "writing", "qualitative notes", "Excel"],
    preferredSkills: ["public health", "health inequalities", "research methods"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Entry-level research project experience",
    educationLevel: "Degree preferred",
    tags: ["health equity", "research", "London", "public health"],
    remoteCompatible: true,
    sector: "Health equity"
  }),
  job({
    id: "nhs-pathway-data-support-oxford",
    title: "NHS Pathway Data Support Assistant",
    company: "Oxford Care Pathways",
    category: "Public health / NHS / service improvement",
    location: "Oxford, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.entry,
    summary: "Maintains pathway trackers, cleans spreadsheet data, and supports improvement teams with basic reports.",
    description: "A structured NHS data support role with clear requirements and training.",
    requiredSkills: ["Excel", "data cleaning", "organisation", "reporting"],
    preferredSkills: ["NHS", "service improvement", "Power BI"],
    requirements: ["hybrid Oxford availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["NHS", "pathway data", "Oxford", "Excel"],
    remoteCompatible: true,
    sector: "NHS data support"
  }),
  job({
    id: "health-service-evaluation-assistant-cambridge",
    title: "Health Service Evaluation Assistant",
    company: "Cambridge Care Evaluation",
    category: "Public health / NHS / service improvement",
    location: "Cambridge, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Assists with survey data, evidence reviews, interview notes, and service evaluation reports.",
    description: "A balanced evaluation role where research methods, data analysis, and writing transfer well.",
    requiredSkills: ["research methods", "Excel", "report writing", "communication"],
    preferredSkills: ["service evaluation", "public health", "qualitative research"],
    requirements: ["hybrid Cambridge availability"],
    experienceRequired: "Entry-level research experience",
    educationLevel: "Degree preferred",
    tags: ["service evaluation", "Cambridge", "research", "public health"],
    remoteCompatible: true,
    sector: "Service evaluation"
  }),

  job({
    id: "scientific-communications-assistant-remote",
    title: "Scientific Communications Assistant",
    company: "ClearScience Studio",
    category: "Scientific communications / documentation / evidence",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Turns scientific information into clear summaries, slide notes, and stakeholder-ready research updates.",
    description: "A remote communications role for candidates with scientific writing and biomedical knowledge.",
    requiredSkills: ["scientific writing", "literature review", "communication", "editing"],
    preferredSkills: ["biomedical science", "medical writing", "stakeholder communication"],
    requirements: ["remote collaboration", "writing samples helpful"],
    experienceRequired: "Entry-level with science writing evidence",
    educationLevel: "Science degree preferred",
    tags: ["scientific communications", "remote", "writing", "biomedical"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Scientific communications"
  }),
  job({
    id: "medical-writing-assistant-london",
    title: "Medical Writing Assistant",
    company: "MedScript Partners",
    category: "Scientific communications / documentation / evidence",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.strong,
    summary: "Supports literature searches, reference checks, draft outlines, and plain-language medical content.",
    description: "A writing-heavy role for biomedical graduates who can turn evidence into structured documents.",
    requiredSkills: ["medical writing", "literature search", "referencing", "editing"],
    preferredSkills: ["biomedical science", "clinical research", "scientific communication"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Entry-level writing portfolio helpful",
    educationLevel: "Life science degree preferred",
    tags: ["medical writing", "London", "literature review", "writing"],
    remoteCompatible: true,
    sector: "Medical communications"
  }),
  job({
    id: "evidence-review-assistant-bham",
    title: "Evidence Review Assistant",
    company: "Midlands Evidence Unit",
    category: "Scientific communications / documentation / evidence",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.entry,
    summary: "Screens literature, extracts evidence, and prepares structured summaries for health and science projects.",
    description: "A strong fit for candidates with literature review, scientific writing, and analytical thinking.",
    requiredSkills: ["literature review", "evidence extraction", "Excel", "scientific writing"],
    preferredSkills: ["health technology assessment", "biomedical science", "critical appraisal"],
    requirements: ["hybrid Birmingham availability"],
    experienceRequired: "University literature review experience accepted",
    educationLevel: "Science degree preferred",
    tags: ["evidence review", "Birmingham", "literature", "science writing"],
    remoteCompatible: true,
    sector: "Evidence review"
  }),
  job({
    id: "research-documentation-officer-manchester",
    title: "Research Documentation Officer",
    company: "Manchester Research Records",
    category: "Scientific communications / documentation / evidence",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Maintains controlled research documents, version logs, audit trails, and project evidence folders.",
    description: "A documentation-focused role suited to careful writers and candidates with regulated research awareness.",
    requiredSkills: ["document control", "quality checks", "organisation", "writing"],
    preferredSkills: ["clinical research", "SOPs", "regulated documents"],
    requirements: ["hybrid Manchester availability"],
    experienceRequired: "Documentation experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["research documentation", "quality", "Manchester", "hybrid"],
    remoteCompatible: true,
    sector: "Research documentation"
  }),
  job({
    id: "scientific-content-coordinator-leeds",
    title: "Scientific Content Coordinator",
    company: "BioBridge Learning",
    category: "Scientific communications / documentation / evidence",
    location: "Leeds, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.entry,
    summary: "Coordinates scientific content calendars, checks source accuracy, and drafts short educational summaries.",
    description: "An entry content role using biomedical knowledge, organisation, and writing skills.",
    requiredSkills: ["scientific writing", "organisation", "editing", "communication"],
    preferredSkills: ["biomedical science", "education content", "literature review"],
    requirements: ["hybrid Leeds availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Science degree preferred",
    tags: ["scientific content", "Leeds", "writing", "education"],
    remoteCompatible: true,
    sector: "Science content"
  }),
  job({
    id: "literature-review-assistant-oxford",
    title: "Literature Review Assistant",
    company: "Oxford Evidence Works",
    category: "Scientific communications / documentation / evidence",
    location: "Oxford, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Supports search strategies, screening logs, evidence tables, and narrative summaries.",
    description: "A precise literature review role for candidates with research methods and scientific writing strengths.",
    requiredSkills: ["literature review", "evidence tables", "Excel", "critical reading"],
    preferredSkills: ["systematic review", "biomedical science", "reference management"],
    requirements: ["hybrid Oxford availability"],
    experienceRequired: "University dissertation or review project",
    educationLevel: "Science degree preferred",
    tags: ["literature review", "Oxford", "evidence", "research"],
    remoteCompatible: true,
    sector: "Evidence synthesis"
  }),
  job({
    id: "regulatory-documentation-assistant-cambridge",
    title: "Regulatory Documentation Assistant",
    company: "Cambridge MedDevices",
    category: "Scientific communications / documentation / evidence",
    location: "Cambridge, hybrid",
    workStyle: "Hybrid",
    level: "Early professional",
    salary: salary.high,
    summary: "Supports regulated document packs, technical files, evidence logs, and product documentation reviews.",
    description: "A more specialised documentation role for candidates interested in medical devices and regulated evidence.",
    requiredSkills: ["documentation", "quality checks", "technical writing", "attention to detail"],
    preferredSkills: ["medical devices", "regulatory affairs", "scientific writing"],
    requirements: ["regulated documentation experience desirable"],
    experienceRequired: "6-18 months documentation or science admin experience",
    educationLevel: "Science degree preferred",
    tags: ["regulatory", "documentation", "Cambridge", "medical devices"],
    remoteCompatible: true,
    seniorityScore: 2,
    sector: "Medical devices"
  }),
  job({
    id: "science-policy-evidence-assistant-remote",
    title: "Science Policy Evidence Assistant",
    company: "PolicyBio Forum",
    category: "Scientific communications / documentation / evidence",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Prepares evidence summaries, stakeholder briefings, and literature notes for science policy projects.",
    description: "A remote evidence role connecting scientific literacy, writing, and public-sector communication.",
    requiredSkills: ["evidence summaries", "writing", "literature review", "stakeholder communication"],
    preferredSkills: ["public health", "policy", "biomedical science"],
    requirements: ["remote collaboration", "briefing writing"],
    experienceRequired: "Entry-level writing or research experience",
    educationLevel: "Degree preferred",
    tags: ["science policy", "remote", "evidence", "writing"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Science policy"
  }),

  job({
    id: "programme-support-officer-health-london",
    title: "Programme Support Officer, Health",
    company: "Future Health Programmes",
    category: "Adjacent transferable early-career roles",
    location: "London, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.standard,
    summary: "Supports health programme plans, stakeholder notes, action trackers, and reporting packs.",
    description: "A transferable role for candidates who want a structured start near healthcare and research operations.",
    requiredSkills: ["programme support", "organisation", "communication", "Excel"],
    preferredSkills: ["healthcare", "service improvement", "report writing"],
    requirements: ["hybrid London availability"],
    experienceRequired: "Entry-level coordination experience helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["programme support", "health", "London", "coordination"],
    remoteCompatible: true,
    sector: "Health programmes"
  }),
  job({
    id: "stakeholder-insight-coordinator-remote",
    title: "Stakeholder Insight Coordinator",
    company: "Civic Listening Lab",
    category: "Adjacent transferable early-career roles",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Entry-level",
    salary: salary.entry,
    summary: "Organises stakeholder feedback, prepares insight notes, and supports research-led community projects.",
    description: "An adjacent insight role where communication, writing, and qualitative analysis matter.",
    requiredSkills: ["stakeholder communication", "note synthesis", "organisation", "writing"],
    preferredSkills: ["research methods", "public health", "community engagement"],
    requirements: ["remote working", "clear writing"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["stakeholder insight", "remote", "research", "communication"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Stakeholder insight"
  }),
  job({
    id: "research-programme-assistant-bham",
    title: "Research Programme Assistant",
    company: "Birmingham Research Partnership",
    category: "Adjacent transferable early-career roles",
    location: "Birmingham, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.entry,
    summary: "Supports project plans, literature searches, event coordination, and research programme reporting.",
    description: "A broad research programme role suited to organised graduates with writing and science interest.",
    requiredSkills: ["research support", "organisation", "Excel", "report writing"],
    preferredSkills: ["biomedical science", "stakeholder communication", "public sector"],
    requirements: ["hybrid Birmingham availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["research programme", "Birmingham", "hybrid", "support"],
    remoteCompatible: true,
    sector: "Research programmes"
  }),
  job({
    id: "knowledge-assistant-health-cambridge",
    title: "Knowledge Assistant, Health Evidence",
    company: "Cambridge Knowledge Exchange",
    category: "Adjacent transferable early-career roles",
    location: "Cambridge, hybrid",
    workStyle: "Hybrid",
    level: "Entry-level",
    salary: salary.standard,
    summary: "Maintains knowledge libraries, prepares evidence summaries, and supports internal research requests.",
    description: "A knowledge-management role where literature review and scientific writing skills transfer well.",
    requiredSkills: ["knowledge management", "literature review", "writing", "organisation"],
    preferredSkills: ["health evidence", "reference management", "research methods"],
    requirements: ["hybrid Cambridge availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["knowledge assistant", "evidence", "Cambridge", "research"],
    remoteCompatible: true,
    sector: "Knowledge management"
  }),
  job({
    id: "graduate-operations-analyst-leeds",
    title: "Graduate Operations Analyst",
    company: "CarePath Operations",
    category: "Adjacent transferable early-career roles",
    location: "Leeds, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.strong,
    summary: "Analyses operational data, maintains trackers, and supports process improvements for healthcare delivery teams.",
    description: "A broader analyst role with healthcare context, useful for exploring transferable data skills.",
    requiredSkills: ["Excel", "operations analysis", "reporting", "process improvement"],
    preferredSkills: ["Power BI", "healthcare", "stakeholder communication"],
    requirements: ["hybrid Leeds availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["operations analyst", "Leeds", "healthcare", "data"],
    remoteCompatible: true,
    sector: "Healthcare operations"
  }),
  job({
    id: "graduate-project-coordinator-digital-care",
    title: "Graduate Project Coordinator, Digital Care",
    company: "Digital Care Works",
    category: "Adjacent transferable early-career roles",
    location: "Manchester, hybrid",
    workStyle: "Hybrid",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Coordinates digital care project tasks, meeting notes, risk logs, and stakeholder updates.",
    description: "An adjacent healthtech project role with training and clear early-career expectations.",
    requiredSkills: ["project coordination", "organisation", "communication", "documentation"],
    preferredSkills: ["digital health", "NHS", "Excel"],
    requirements: ["hybrid Manchester availability"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree or equivalent experience",
    tags: ["project coordinator", "digital care", "Manchester", "healthtech"],
    remoteCompatible: true,
    sector: "Digital care"
  }),
  job({
    id: "clinical-operations-assistant-oxford",
    title: "Clinical Operations Assistant",
    company: "Oxford Clinical Support",
    category: "Adjacent transferable early-career roles",
    location: "Oxford, hybrid",
    workStyle: "Hybrid",
    level: "Career-change friendly",
    salary: salary.entry,
    summary: "Supports rota trackers, operational reports, meeting actions, and clinical service administration.",
    description: "A healthcare operations role that can suit candidates seeking a calmer entry point into health systems.",
    requiredSkills: ["administration", "Excel", "communication", "organisation"],
    preferredSkills: ["NHS", "healthcare volunteering", "service improvement"],
    requirements: ["hybrid Oxford availability"],
    experienceRequired: "Entry-level admin or volunteering helpful",
    educationLevel: "Degree or equivalent experience",
    tags: ["clinical operations", "Oxford", "healthcare", "entry-level"],
    remoteCompatible: true,
    sector: "Clinical operations"
  }),
  job({
    id: "graduate-research-coordinator-remote",
    title: "Graduate Research Coordinator",
    company: "EvidenceFlow Research",
    category: "Adjacent transferable early-career roles",
    location: "Remote-first UK",
    workStyle: "Remote-first",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Coordinates research trackers, interview notes, evidence folders, and team updates for multi-sector projects.",
    description: "A remote-friendly role testing how ORBY handles broader transferable research matches.",
    requiredSkills: ["research coordination", "writing", "Excel", "organisation"],
    preferredSkills: ["health research", "stakeholder communication", "evidence review"],
    requirements: ["remote collaboration", "UK working hours"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["research coordinator", "remote", "evidence", "graduate"],
    remoteCompatible: true,
    locationFlexibility: "Remote-first UK",
    sector: "Research coordination"
  }),

  job({
    id: "senior-forensic-scientist-casework",
    title: "Senior Forensic Scientist, Casework",
    company: "National Casework Laboratory",
    category: "Deliberate lower-priority / filtering tests",
    location: "London",
    workStyle: "On-site",
    level: "Senior",
    salary: salary.competitive,
    summary: "Leads complex casework, signs expert reports, and mentors forensic scientists.",
    description: "A deliberate senior poor-fit role requiring extensive direct forensic casework experience.",
    requiredSkills: ["expert witness reporting", "casework leadership", "forensic interpretation"],
    preferredSkills: ["court experience", "toxicology", "DNA interpretation"],
    requirements: ["5+ years forensic casework", "security clearance", "expert report sign-off"],
    experienceRequired: "5+ years",
    educationLevel: "BSc plus extensive professional forensic experience",
    tags: ["senior", "forensic", "poor-fit", "casework"],
    seniorityScore: 5,
    earlyCareerFriendly: false,
    trainingProvided: false,
    requiresSecurityClearance: true,
    requiresPriorForensicExperience: true,
    status: "active",
    sector: "Forensic science"
  }),
  job({
    id: "principal-bioinformatics-scientist",
    title: "Principal Bioinformatics Scientist",
    company: "GenomeScale Therapeutics",
    category: "Deliberate lower-priority / filtering tests",
    location: "Cambridge",
    workStyle: "Hybrid",
    level: "Senior",
    salary: salary.competitive,
    summary: "Leads high-throughput omics analysis and Python/R pipeline development for discovery teams.",
    description: "A deliberate poor fit for entry-level users because it requires advanced coding, PhD-level expertise, and senior leadership.",
    requiredSkills: ["Python", "R", "bioinformatics", "pipeline development", "leadership"],
    preferredSkills: ["PhD", "machine learning", "cloud computing"],
    requirements: ["PhD required", "5+ years bioinformatics experience"],
    experienceRequired: "5+ years",
    educationLevel: "PhD required",
    tags: ["senior", "PhD", "Python", "bioinformatics", "poor-fit"],
    seniorityScore: 5,
    earlyCareerFriendly: false,
    trainingProvided: false,
    requiresPhD: true,
    requiresPython: true,
    status: "active",
    sector: "Bioinformatics"
  }),
  job({
    id: "field-sales-executive-medical-devices",
    title: "Field Sales Executive, Medical Devices",
    company: "QuotaMed Sales",
    category: "Deliberate lower-priority / filtering tests",
    location: "South West England",
    workStyle: "On-site",
    level: "Early professional",
    salary: salary.competitive,
    summary: "Drives territory sales, cold outreach, and revenue growth for device accounts.",
    description: "A deliberate lower-priority role: healthcare-adjacent but sales-led, driving-heavy, and weakly aligned with research/lab goals.",
    requiredSkills: ["sales", "cold outreach", "driving", "targets"],
    preferredSkills: ["medical devices", "account management"],
    requirements: ["full driving licence", "territory travel", "sales targets"],
    experienceRequired: "1-2 years sales experience",
    educationLevel: "Degree not required",
    tags: ["sales", "driving", "poor-fit", "medical devices"],
    earlyCareerFriendly: false,
    trainingProvided: true,
    requiresDriving: true,
    requiresTravel: true,
    status: "active",
    sector: "Sales"
  }),
  job({
    id: "graduate-finance-operations-analyst",
    title: "Graduate Finance Operations Analyst",
    company: "LedgerWorks Capital",
    category: "Deliberate lower-priority / filtering tests",
    location: "London",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.high,
    summary: "Supports financial reconciliations, operations reports, and transaction monitoring.",
    description: "A deliberate weak match for biomedical/forensic profiles despite being graduate-level and analytical.",
    requiredSkills: ["finance", "reconciliation", "Excel", "operations"],
    preferredSkills: ["accounting", "financial services"],
    requirements: ["on-site London work", "finance interest"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["finance", "unrelated", "graduate", "poor-fit"],
    status: "active",
    sector: "Finance"
  }),
  job({
    id: "phd-clinical-research-scientist",
    title: "Clinical Research Scientist",
    company: "Advanced Immunology Trials",
    category: "Deliberate lower-priority / filtering tests",
    location: "Oxford",
    workStyle: "On-site",
    level: "Mid-level",
    salary: salary.competitive,
    summary: "Designs clinical study protocols and leads scientific interpretation for immunology trials.",
    description: "A deliberate filter test requiring a PhD and deeper protocol leadership than an entry-level user is likely to have.",
    requiredSkills: ["protocol design", "GCP", "immunology", "scientific leadership"],
    preferredSkills: ["PhD", "clinical trials", "publications"],
    requirements: ["PhD required", "3+ years clinical research"],
    experienceRequired: "3+ years",
    educationLevel: "PhD required",
    tags: ["PhD", "clinical research", "mid-level", "poor-fit"],
    seniorityScore: 4,
    earlyCareerFriendly: false,
    trainingProvided: false,
    requiresPhD: true,
    requiresGCP: true,
    status: "active",
    sector: "Clinical research"
  }),
  job({
    id: "expired-lab-assistant-glasgow",
    title: "Laboratory Assistant",
    company: "NorthLab Diagnostics",
    category: "Deliberate lower-priority / filtering tests",
    location: "Glasgow",
    workStyle: "On-site",
    level: "Entry-level",
    salary: salary.low,
    summary: "Expired test listing for sample preparation and lab records.",
    description: "Included to confirm ORBY does not show expired jobs in top recommendations.",
    requiredSkills: ["lab safety", "sample preparation", "records"],
    preferredSkills: ["biomedical science"],
    requirements: ["on-site Glasgow"],
    experienceRequired: "Entry-level",
    educationLevel: "Science background",
    tags: ["expired", "lab", "filter-test"],
    status: "expired",
    sector: "Diagnostics"
  }),
  job({
    id: "expired-data-entry-finance",
    title: "Finance Data Entry Assistant",
    company: "ReconcileNow",
    category: "Deliberate lower-priority / filtering tests",
    location: "Manchester",
    workStyle: "On-site",
    level: "Entry-level",
    salary: salary.low,
    summary: "Expired unrelated data entry listing for finance operations.",
    description: "Included to test status filtering and relevance ranking.",
    requiredSkills: ["data entry", "finance", "Excel"],
    preferredSkills: ["accounts"],
    requirements: ["on-site Manchester"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree not required",
    tags: ["expired", "finance", "filter-test"],
    status: "expired",
    sector: "Finance"
  }),
  job({
    id: "needs-checking-remote-overseas-role",
    title: "Remote Health Research Assistant, International",
    company: "Global Evidence Desk",
    category: "Deliberate lower-priority / filtering tests",
    location: "Remote - international",
    workStyle: "Remote",
    level: "Entry-level",
    salary: salary.competitive,
    summary: "Remote health evidence role with unclear working-abroad eligibility and contract location rules.",
    description: "Included to test extra-requirement handling where remote-from-abroad rules should be checked.",
    requiredSkills: ["literature review", "writing", "remote collaboration"],
    preferredSkills: ["public health", "languages"],
    requirements: ["location eligibility unclear"],
    experienceRequired: "Entry-level",
    educationLevel: "Degree preferred",
    tags: ["needs_checking", "remote", "international", "eligibility"],
    remoteCompatible: true,
    locationFlexibility: "Needs checking",
    status: "needs_checking",
    sector: "Health research"
  }),
  job({
    id: "needs-checking-security-clearance-forensic",
    title: "Forensic Evidence Trainee",
    company: "SecureLab National",
    category: "Deliberate lower-priority / filtering tests",
    location: "UK-wide",
    workStyle: "On-site",
    level: "Graduate / entry level",
    salary: salary.standard,
    summary: "Forensic trainee listing with unclear security clearance and relocation requirements.",
    description: "Included to test needs-checking status and forensic eligibility flags.",
    requiredSkills: ["evidence handling", "documentation", "lab safety"],
    preferredSkills: ["forensic science", "chain of custody"],
    requirements: ["security clearance unclear", "relocation may be required"],
    experienceRequired: "Entry-level",
    educationLevel: "Science degree preferred",
    tags: ["needs_checking", "forensic", "security clearance"],
    requiresSecurityClearance: true,
    status: "needs_checking",
    sector: "Forensic science"
  })
];

window.seededJobs = seededJobs;
